### ISSUE TITLE
Alternative Mic GSA4737H12-F26-6P at JLCPCB

### ISSUE THREAD

**Issue by ChrisX1809** [NandXor96/USBWLEDC#2]
Hey, 

is there an alternativ way for the mic GSA4737H12-F26-6P?
I tried to order a assembled PCB at JLCPCB but the part GSA4737H12-F26-6P isn't available. Tried to order the parts at JLCPCB Service, but minimum order quantity is 2000 . Soldering this part manual seems to be difficult because of the soldering pads below.

Probably there is an alternativ component possible without adjusting the pcb layout. 

I like the project and want to order an assembled PCB. So perhaps anyone has a good idea to solve.

Thx
Chris

**Comment by NandXor96** [comment]
The microphone LMD4737T261-OAC02 (C19267425) should work as replacement. 
However, I haven't tested it myself, so I can't guarantee its functionality. If you do try it, please share your experience with us.
